# Generated by Django 5.2.13 on 2026-04-16 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_code", models.CharField(max_length=10, unique=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "volume_segment",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("current_stock", models.FloatField(default=0)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("lead_time_weeks", models.IntegerField(default=2)),
                ("reorder_level", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                ("prediction", models.FloatField()),
                ("lower_bound", models.FloatField()),
                ("upper_bound", models.FloatField()),
                (
                    "model_used",
                    models.CharField(
                        choices=[
                            ("XGBoost", "XGBoost"),
                            ("Holt-Winters", "Holt-Winters"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_tier", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forecasting.medicine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_sold", models.FloatField()),
                ("date", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forecasting.medicine",
                    ),
                ),
            ],
        ),
    ]
